version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - todo

  todo-app:
    image: niklasappelquist/api-demo:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - todo
    depends_on:
      - rabbitmq
    environment:
      # MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672

  todo-worker:
    image: niklasappelquist/api-worker:latest
    mem_limit: 700m
    ports:
      - "8090:8080"
    networks:
      - todo
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672

networks:
  todo:
